language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - CS_CHECK=true
    - php: 7.3
    - php: 7.4

before_install:
  - phpenv config-rm xdebug.ini || return 0

before_script:
  - composer self-update
  - composer install

script:
  - if [[ $CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs ; fi
  - ./vendor/bin/phpunit
