name: Run CI

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1']
        dependencies: ['normal', 'authoritative']

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        if: matrix.dependencies == 'normal'
        run: composer install --prefer-dist
        env:
          COMPOSER_ROOT_VERSION: dev-master

      - name: Install dependencies
        if: matrix.dependencies == 'authoritative'
        run: composer install --prefer-dist --classmap-authoritative
        env:
          COMPOSER_ROOT_VERSION: dev-master

      - name: Run Phpunit
        run: ./vendor/bin/phpunit

      - name: Run PhpCs
        run: ./vendor/bin/phpcs -q --report=checkstyle | ./vendor/bin/cs2pr

      - name: Run Infection
        run: phpdbg -qrr vendor/bin/infection
